#! /bin/bash

if [ "$1" = "--unattended" ]
then
    UNATTENDED=true
    echo "unattended"
elif [ "$1" = "-f" ]
then
    UNATTENDED=true
else
    UNATTENDED=false
fi

cd $(dirname $0)
cd bin
. initialize_setupscript

mkdir -v sdk
mkdir -v installers

if $UNATTENDED 
then
    echo "Running unattended..."
else
    while true; do
	echo "You may run this scrip unattended."
	read -p "Do you wnat to do that? (Y/N)" yn
	case $yn in
            [Jj]* ) UNATTENDED=true; break;;
            [Yy]* ) UNATTENDED=true; break;;
            [Nn]* ) break;;
            * ) echo "Please answer yes or no.";;
	esac
    done
fi

if $UNATTENDED
then
    launch_installer=true   
    echo "This will install a fresh alfresco ${ALFRESCO_VERSION}"
    echo "in $INSTALL_DIR"
else
    echo "This may install a fresh alfresco ${ALFRESCO_VERSION}"
    echo "in $INSTALL_DIR"
    launch_installer=false
    while true; do
	echo "Do you want to run the installer?"
	read -p "This will wipe any previous install at ${INSTALL_DIR}? (Y/N)" yn
	case $yn in
            [Jj]* ) launch_installer=true; break;;
            [Yy]* ) launch_installer=true; break;;
            [Nn]* ) break;;
            * ) echo "Please answer yes or no.";;
	esac
    done
fi


if $launch_installer
then
    bin/download_installer

    echo "Wiping any previous installation in $INSTALL_DIR"
    rm -rf $INSTALL_DIR

    echo "Launching the community installer"
    bin/install_alfresco_unatended

    # Creating a link to the installation
    # -----------------------------------
    bin/create_alfresco_softlink
fi


if [ "$DB_HOST" = "localhost" ]
then
    has_mysql=false
    if dpkg-query -l mysql-server > /dev/null
    then
	echo "You have mysql-server installd locally."
	has_mysql=true
    else
	echo "Following steps requires a mysql-server"
	echo "You do not have mysql-server installed locally!"
	if $UNATTENDED
	then
	    install_mysql=true
	else
	    install_mysql=false
	    while true; do
		read -p "Do you want to install mysql locally (Y/N)?" yn
		case $yn in
		    [Jj]* ) install_mysql=true; break;;
		    [Yy]* ) install_mysql=true; break;;
		    [Nn]* ) break;;
		    * ) echo "Please answer yes or no.";;
		esac
	    done
	fi

	if $install_mysql
	then
	    echo "Installing mysql server"
	    bin/install_mysql_server
	    has_mysql=true
	fi
    fi
    if $has_mysql
    then
	echo "Following steps require a a properly configured mysql-server"
	if $UNATTENDED
	then
	    configure_mysql=true
	else
	    configure_mysql=false
	    while true; do
		read -p "Do you want to configure the mysql-server installed locally for alfresco (Y/N)?" yn
		case $yn in
		    [Jj]* ) configure_mysql=true; break;;
		    [Yy]* ) configure_mysql=true; break;;
		    [Nn]* ) break;;
		    * ) echo "Please answer yes or no.";;
		esac
	    done
	fi

	if $configure_mysql
	then
	    echo "Configuring mysql server"
	    bin/configure_mysql_server
	fi
    fi
fi

if ! $UNATTENDED
then
    echo "=========================================================================================="
    echo "IMPORTANT: Next steps require an existing (fresh)"
    echo "           alfresco installation in $INSTALL_DIR" 
    echo "           and also a properly configured mysql-server at $DB_HOST"
    echo "=========================================================================================="
    while true; do
	read -p "Do you wish to go on and configure the alfresco installation for local development usage (Y/N)?" yn
	case $yn in
            [Jj]* ) break;;
            [Yy]* ) break;;
            [Nn]* ) exit 0;;
        * ) echo "Please answer yes or no.";;
	esac
    done
fi

# Create DB
# ---------
echo "(Re)creating a db"
bin/dbrecreate

# Start scripts and environment config
# ------------------------------------
bin/setup_config

# Fix cert problems
# -----------------
echo "Fix epired certs problem"
pushd $INSTALL_DIR/alf_data/keystore
./generate_keystores.sh
popd

#cp files/$ALFRESCO_VERSION/generate_keystores.sh $INSTALL_DIR/alf_data/keystore/
#pushd $INSTALL_DIR/alf_data/keystore
#chmod +x  generate_keystores.sh
#./generate_keystores.sh
#popd

# Backup empty alf-data
# ---------------------
echo "Backing up initial alf data"
bin/backup_alfdata "initial"

# MySQL connector
# ---------------
echo "Installing MySQL connector"
cp -v files/$ALFRESCO_VERSION/mysql-connector-*.jar $INSTALL_DIR/tomcat/lib

# Move Alf Data
# -------------
if $RELOCATE_ALF_DATA
then
    echo "Relocating alf data"
    sudo mkdir -p $ALF_DATA_CONTEXT_DIR
    sudo chown -R $USER:$USER $ALF_DATA_CONTEXT_DIR
    rm -rf $ALF_DATA_CONTEXT_DIR/alf_data

    mv -v $INSTALL_DIR/alf_data $ALF_DATA_CONTEXT_DIR
    ln -s $ALF_DATA_CONTEXT_DIR/alf_data $INSTALL_DIR/alf_data
else
    echo "No relocation of alf data"
fi

# Swedish
# -------

if [ -e files/$ALFRESCO_VERSION/share_sv_SE-*.jar ]
then
    echo "Configuring swedish"
    cp files/$ALFRESCO_VERSION/share_sv_SE-*.jar $INSTALL_DIR/tomcat/shared/lib
else
    echo "Unable to configue swedish - no translation jar found"
fi

# Installing run scripts
# ----------------------
bin/install_run_scripts


# Backup installation
# -------------------
bin/backup_installation


# SDK
# ---
bin/install_sdk