#! /bin/bash

DB_HOST=localhost
DB_NAME=alfresco42e 
DB_USER=alfresco
DB_PW=alfresco
DB_ROOT_USER=root
DB_ROOT_PW=Altrusoft09
JDBC_DRIVER="org.gjt.mm.mysql.Driver"
JDBC_URL="jdbc:mysql://$DB_HOST/$DB_NAME?useUnicode=yes&characterEncoding=UTF-8"
