#! /bin/bash
# Config for ALFRESCO_VERSION 4.2.e

# User bin
#    USER_BIN="$HOME/.bin" 
#    USER_BIN="$HOME/bin"
 
# Program dir
if [[ $EUID -ne 0 ]] 
then
    PROGRAM_DIR=$HOME/Program
    #PROGRAM_DIR=/opt/$USER
    SOFTLINK_DIR=$HOME/Program
else
    PROGRAM_DIR=/opt
    SOFTLINK_DIR=/opt
fi

# Database
DB_USE_MYSQL=false

ALFRESCO_COMPONENTS="javaalfresco,alfrescosharepoint,alfrescogoogledocs,libreofficecomponent"
ALFRESCO_DISABLED_COMPONENTS="alfrescowcmqs"

if $DB_USE_MYSQL
then
    ALFRESCO_DISABLED_COMPONENTS="postgres,$ALFRESCO_DISABLED_COMPONENTS"
else
    ALFRESCO_COMPONENTS="postgres,$ALFRESCO_COMPONENTS"
fi

INSTALL_DIR=$PROGRAM_DIR/alfresco-$ALFRESCO_VERSION

# If RELOCATE_ALF_DATA set to true alf data will be moved to
# ALF_DATA_CONTEXT_DIR during install
RELOCATE_ALF_DATA=true
ALF_DATA_CONTEXT_DIR=/var/alfresco/alfresco-$ALFRESCO_VERSION

#ALF_JAVA_HOME=$JAVA_HOME
#ALF_JAVA_HOME=/usr/lib/jvm/java-6-sun
# The bundled version of java works best, i.e:
ALF_JAVA_HOME=$INSTALL_DIR/java

ALF_ADMIN_PW="123456"



