#!/bin/bash

workdir=$(pwd)
backup_name=$1

cd $(dirname $0)

if [ ! -z "$backup_name" ]
then
    echo "Restoring backup: $backup_name of Alfresco db and alfdata from: $workdir"
    backup_name="_${backup_name}"
else
    echo "Restoring Alfresco db and alfdata from: $workdir" 
fi


while true; do
    read -p "Do you wish to do that?" yn
    case $yn in
        [Jj]* ) break;;
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

cd $workdir

if [ ! -e "alf_data${backup_name}.tgz" ]
then
    echo "Unable to find backup of alfdata: $workdir/alf_data${backup_name}.tgz"
    exit 1
fi
if [ ! -e "<DB_NAME>${backup_name}.SQL" ]
then
    echo "Unable to find backup od database: $workdir/<DB_NAME>${backup_name}.SQL"
    exit 1
fi

./alfstop
echo "Restoring alfdata from ${workdir}/alf_data${backup_name}.tgz"
cd <INSTALL_DIR>
rm -rf alf_data
tar xvzf "${workdir}/alf_data${backup_name}.tgz"

echo "Restoring db from ${workdir}/<DB_NAME>${backup_name}.SQL"
mysql --verbose --user=<DB_ROOT_USER> --password=<DB_ROOT_PW> <DB_NAME> < "${workdir}/<DB_NAME>${backup_name}.SQL"








