#!/bin/bash

cd $(dirname $0)

echo "Wiping Alfresco data and configuration *completely* - flush db and restore original installation"
while true; do
    read -p "Do you wish to do that? " yn
    case $yn in
        [Jj]* ) break;;
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

./alfstop

install_dir=$(readlink -f  <INSTALL_DIR>)

cd ${install_dir}/..

if [ ! -e  alfresco-<ALFRESCO_VERSION>-backup.tgz ]
then
    echo "Found no intial alfresco installation to restore - exiting"
    exit 9
fi
echo "Removing current installation"
rm -rf alfresco-<ALFRESCO_VERSION>
echo "Restoring initial installation"
tar xzf alfresco-<ALFRESCO_VERSION>-backup.tgz

echo "Dropping db"
/usr/bin/mysql -u<DB_ROOT_USER> -h<DB_HOST> -p<DB_ROOT_PW> << eof
DROP DATABASE IF EXISTS <DB_NAME>;
eof

echo "Creating a fresh db"
if [ "<DB_HOST>" = "localhost" ]
then
    /usr/bin/mysql -u<DB_ROOT_USER> -h<DB_HOST> -p<DB_ROOT_PW> << eof
CREATE DATABASE <DB_NAME>;
GRANT ALL PRIVILEGES ON <DB_NAME>.* TO '<DB_USER>'@'localhost' WITH GRANT OPTION;
eof
else
    /usr/bin/mysql -u<DB_ROOT_USER> -h<DB_HOST> -p<DB_ROOT_PW> << eof
CREATE DATABASE <DB_NAME>;
GRANT ALL PRIVILEGES ON <DB_NAME>.* TO '<DB_USER>'@'%' WITH GRANT OPTION;
eof
fi





